### ISSUE TITLE
怎么用的 能否给个教程

### ISSUE THREAD

**Issue by lil-hope** [young-zy/v2rayRestfulApi#1]

**Comment by young-zy** [comment]
仍然在开发中，但是由于个人原因，进度十分缓慢。
现在能用的应该只有logger重启和查询用量。
启动的方法在readme里有，这里就不写了。
调用方法：
举例：https://github.com/young-zy/v2rayRestfulApi/blob/master/stats/command/command.proto#L54
get后面的就是path，没在path里的参数默认会在请求parameter中

附言：
主要是因为 v2ray 本身对HandlerService 中配置自己实现了一个序列化，没办法使用gateway方便地生成代码，暂时没有太多时间对这个进行研究（其实是我没有需求），因此handler service的适配被暂时搁置了
